### ISSUE TITLE
Informações sobre a LIB

### ISSUE THREAD

**Issue by alissonsilvas** [adhenrique/zoop#4]
Estamos fechando contrato com a Zoop essa Lib está sendo usada em produção? ao decorrer da adaptação vou contribuir com ela.

**Comment by adhenrique** [comment]
@AlissonSilvaCe sim está sendo usada em produção. Algumas pessoas tem contribuído também, e eu na maneira do possível a atualizo. Mas sinta-se a vontade para contribuir.

Muito obrigado.

**Comment by thiagobueno** [comment]
Conhecem alguma em Laravel 4 ou apenas PHP?

**Comment by adhenrique** [comment]
@thiagobueno Não conheço, infelizmente.

**Comment by thiagobueno** [comment]
> @thiagobueno Não conheço, infelizmente.

Pra fazer essa você usou alguma base ou fez do zero?

**Comment by adhenrique** [comment]
> > @thiagobueno Não conheço, infelizmente.
> 
> Pra fazer essa você usou alguma base ou fez do zero?

Essa eu fiz do zero.  E se vc tiver interesse em enviar um PR, será muito gratificante.

**Comment by alissonsilvas** [comment]
A Lib do @adhenrique está muito boa, problema é o time de integração da Zoop.

**Comment by thiagobueno** [comment]
@adhenrique Meu problema é que o projeto do cliente está em Laravel 4.2 usando o Pagar Me - PHP, e eles mudaram para a Zoop, mas a própria Zoop não oferece uma API em PHP.

**Comment by adhenrique** [comment]
Obrigado pelo elogio @AlissonSilvaCe 

@thiagobueno Sim. Na época em que utilizei a Zoop também tive a mesma necessidade, então desenvolvi essa lib. Mas eu estava utilizando o Laravel 5.3 - que aliás, precisa de atualizações para atender o Laravel 5.8.

**Comment by thiagobueno** [comment]
@adhenrique Complicado, ou eu vou ter que fazer uma Lib em PHP ou Mudar o Projeto pra Laravel 5.3 kkkkk realmente não sei qual vai dar menos trabalho.

Sua Lib parece ser ótima e com todas as funções disponíveis.

A uns meses atrás estava em um novo projeto e ja fazendo ele no Laravel 5, porem tenho pouco conhecimento do mesmo, e se eu fosse fazer uma Lib teria que ser baseado na sua, pois é a unica em PHP que achei até o momento.

**Comment by adhenrique** [comment]
hahahaha @thiagobueno 
Eu, particularmente, atualizaria o projeto. Mas há algumas ressalvas, inclusive a dependência do php. Pra atualizá-lo você teria que modificar toda sua estrutura de infra.

Portanto, talvez seja mais viável utilizar minha lib como exemplo. As possíveis mudanças que ocorrerão serão mais a respeito do suporte do php, algo como array(), callbacks, etc...

Eu poderia fazer uma versão para o Laravel 4, mas infelizmente eu não tenho tokens de acesso a aplicação da Zoop =/

**Comment by thiagobueno** [comment]
@adhenrique Sim, eu iniciei um projeto totalmente do zero ja com Laravel 5.7 e o projeto do cliente é um pouco grande pra fazer a alteração do framework (e provavelmente não vai pagar pela mudança).

Estou entrando em contato com eles, pois falaram que tinha uma api em PHP, qualquer coisa entro em contato, valeu cara!
